---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/run-cf-release-unit-tests

inputs:
- name: cf-release-develop
- name: runtime-ci

run:
  path: runtime-ci/scripts/ci/run-cf-release-unit-tests/task

params:
  CF_RELEASE_DIR:
