---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state
- name: ops-file

run:
  path: runtime-ci/tasks/bosh-extend-cloud-config/task

params:
  BBL_STATE_DIR:
  OPS_FILE_PATH:
