---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: runtime-ci
- name: cf-deployment
- name: stemcell

outputs:
- name: exported-release

run:
  path: runtime-ci/tasks/compile-release-docker-cpi/task

params:
  RELEASE_NAME:
  BOSH_RELEASE:
  STEMCELL_OS: ubuntu-trusty
