---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: cf-deployment
- name: runtime-ci
outputs:
- name: exported-release
params:
  BOSH_RELEASE:
  STEMCELL_OS: ubuntu-trusty
  DEPLOYMENT_NAME: cf-compilation

run:
  path: runtime-ci/tasks/bosh-export-release/task
