---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-and-spiff

inputs:
- name: routing-release
- name: stubs-repo
- name: runtime-ci
- name: cf-manifest
- name: diego-manifest

outputs:
- name: routing-manifest

run:
  path: runtime-ci/tasks/generate-routing-manifest/task

params:
  CF_MANIFEST_PATH:
  DIEGO_MANIFEST_PATH:
  PROPERTY_OVERRIDES_PATH:
  IAAS_SETTINGS_PATH:
  PERSISTENT_DISK_OVERRIDES_PATH:
  INSTANCE_COUNT_OVERRIDES_PATH:
