---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state # - The Director's `bbl-state.json`

run:
  path: runtime-ci/tasks/bosh-run-errand/task

params:
  BBL_STATE_DIR:
  # - Optional
  # - Path to the directory containing the `bbl-state.json` file
  # - The path is relative to root of the `bbl-state` input
  # - Defaults to the root of the `bbl-state` input

  DEPLOYMENT_NAME: cf
  ERRAND_NAME:
