---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci
- name: cf-deployment-version
- name: cf-deployment-release-candidate
- name: cf-deployment-transition-compatibility
outputs:
- name: updated-cf-deployment-transition-compatibility
run:
  path: runtime-ci/tasks/record-transition-version/task
