---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: cf-deployment
- name: ops-files
- name: vars-files
- name: runtime-ci

run:
  path: runtime-ci/tasks/bosh-dry-run/task

params:
  VARS_FILES:
  DEPLOYMENT_NAME_SUFFIX: ""
