---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci
- name: repo
- name: manifest
- name: ops-file
- name: commit-message

outputs:
- name: updated-repo

run:
  path: runtime-ci/tasks/commit-generated-manifest/task

params:
  MANIFEST_NAME:
  OPS_FILE_NAME:
  OPS_FILE_DESTINATION:
  MANIFEST_DESTINATION:
  COMMIT_MESSAGE_PATH: commit-message.txt
  COMMIT_ALL_OPS_FILES: false
  # Commits all ops files changes
  # rather than committing individual ops files
