---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
  - name: env-repo

outputs:
- name: dynamic-bosh-source

run:
  path: runtime-ci/tasks/generate-dynamic-bosh-source/task

params:
  BBL_STATE_DIR: bbl-state
