---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: runtime-ci
  - name: cf-release
  - name: diego-release
  - name: cflinuxfs2-release
  - name: garden-runc-release
  - name: cf-deployment
  - name: cf-deployment-transition
  - name: routing-release
  - name: cf-networking-release
  - name: grootfs-release
  - name: cf-deployment-transition-compatibility

outputs:
  - name: updated-r2d2-compatibility

params:
  COMPATIBILITY_FILE: transition-compatibility.csv

run:
  path: runtime-ci/tasks/record-r2d2-compatible-versions/task
