---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundrylondon/backup-and-restore

inputs:
- name: runtime-ci
- name: disaster-recovery-acceptance-tests
  path: src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests
- name: bbr-binary-release
- name: drats-config

run:
  path: runtime-ci/tasks/run-drats/task

params:
  FOCUSED_SUITE_NAME:
  SKIP_SUITE_NAME:
  DEFAULT_TIMEOUT_MINS: