---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-and-sshuttle

inputs:
- name: runtime-ci
- name: disaster-recovery-acceptance-tests
  path: src/github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests
- name: bbr-binary-release
- name: environment

run:
  path: runtime-ci/tasks/run-drats/task_new

params:
  BBL_STATE_DIR:
  CONFIG_FILE_PATH:
  DEFAULT_TIMEOUT_MINS:
  FOCUSED_SUITE_NAME:
  SKIP_SUITE_NAME:
