---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/golang-17

inputs:
- name: runtime-ci
- name: deployment-configuration
- name: cf-mysql-release
- name: stemcell

outputs:
- name: commit-message
- name: deployment-manifest

run:
  path: runtime-ci/tasks/update-release-mysql/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  DEPLOYMENT_CONFIGURATION_PATH: cf-deployment.yml
  DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
