---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cats-concourse-task

inputs:
- name: runtime-ci
- name: windows-acceptance-tests
- name: integration-config

run:
  path: runtime-ci/tasks/run-wats/task

params:
  CONFIG_FILE_PATH: wats_integration_config.json
