#!/bin/bash -eu

## Prerequisites
type texplate > /dev/null
type bosh > /dev/null

## Prerequisites
# old_job=$(mktemp)
# new_job=$(mktemp)
old_job=update-orig.yml
new_job=update-new.yml
releases="haproxy
          broker-registrar
          backup-and-restore-sdk
          nfs-volume
          binary-buildpack
          capi
          cf-app-sd
          cf-networking
          silk
          cf-smoke-tests
          cf-syslog-drain
          cflinuxfs2
          consul
          diego
          dotnet-core-buildpack
          garden-runc
          go-buildpack
          java-buildpack
          loggregator
          cf-mysql
          nats
          nodejs-buildpack
          php-buildpack
          postgres
          python-buildpack
          routing
          ruby-buildpack
          staticfile-buildpack
          statsd-injector
          uaa
         "

for r in $releases; do
    set +e
    
        if [ $r = "backup-and-restore-sdk" ]; then
            bosh int ../update-releases.yml --path /jobs/name=update-bbr > $old_job
            sed -i .bak 's/bbr/backup-and-restore-sdk/g' $old_job
            rm -f $old_job.bak
        else
            bosh int ../update-releases.yml --path /jobs/name=update-$r > $old_job
        fi
        
        bosh int <(texplate execute template.yml --input-file input.yml) --path /jobs/name=update-$r > $new_job

        diff_output=$(diff $old_job $new_job)
        exit_code=$?
        
    set -e

    if [ $exit_code != 0 ]; then
        echo "update-$r jobs have diverged: $diff_output"
        exit 2
    else
        echo "update-$r jobs are in sync"
        rm -f $old_job $new_job
    fi
done
