---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: chore-bot-source

run:
  path: runtime-ci/tasks/run-chore-bot-tests/task
