---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: ops-files
- name: runtime-ci
- name: bosh-io-release
- name: compiled-release-tarball
- name: current-commit-message
  optional: true

outputs:
- name: updated-compiled-releases-ops-file
- name: commit-message

run:
  path: runtime-ci/tasks/update-compiled-release-ops/task

params:
  RELEASE_NAME:
  COMMIT_MESSAGE_PATH: commit-message.txt
  PATH_TO_OPS_FILE: use-compiled-releases.yml
