---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state
- name: vars-store

outputs:
- name: drats-config

run:
  path: runtime-ci/tasks/generate-drats-config/task

params:
  DEPLOYMENT_NAME: cf
  SYSTEM_DOMAIN:
  BBL_STATE_DIR:
  VARS_STORE_FILE: deployment-vars.yml
  SSH_DESTINATION_CIDR: "10.0.0.0/8"
