---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: env-repo
- name: bosh-deployment
- name: terraform

outputs:
- name: updated-env-repo

run:
  path: runtime-ci/tasks/bosh-delete-env/task

params:
  GCP_PROJECTID:
  GCP_CREDENTIALS:
  GCP_ZONE:
