---
groups:
- name: bbr
  jobs:
  - acquire-pool
  - deploy
  - run-drats

- name: infrastructure
  jobs:
  - add-claimed-lock
  - remove-claimed-lock
  - setup-infrastructure
  - destroy-infrastructure
  - run-bosh-cleanup

resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: bbr-pool
  type: pool
  source:
    uri: git@github.com:cloudfoundry/relint-ci-pools
    branch: master
    pool: bbr
    private_key: {{relint_ci_pools_readwrite_deploy_key}}
- name: baba-yaga-env-director-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/baba-yaga-env.git
    private_key: {{baba_yaga_env_readwrite_deploy_key}}
    paths:
    - bbl-state.json
    - google_account_creds.json
- name: baba-yaga-env-integration-configs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/baba-yaga-env.git
    private_key: {{baba_yaga_env_readwrite_deploy_key}}
    paths:
    - integration_config.json
- name: baba-yaga-env-vars-store
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/baba-yaga-env.git
    private_key: {{baba_yaga_env_readwrite_deploy_key}}
    paths:
    - deployment-vars.yml
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: cf-deployment-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: drats-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry-incubator/disaster-recovery-acceptance-tests.git
- name: bbr-github-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: bosh-backup-and-restore

- name: daily
  type: time
  source:
    start: 3:00 -0700
    stop: 3:30 -0700
    interval: 24h

jobs:
- name: add-claimed-lock
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - get: runtime-ci
  - task: prepare-to-modify-pool-resource
    file: runtime-ci/tasks/prepare-to-modify-pool-resource/task.yml
    params:
      NAME: baba-yaga
    output_mapping:
      pool-resource: bbr-pool
  - put: bbr-pool
    params: {add_claimed: bbr-pool}

- name: setup-infrastructure
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - get: bbr-pool
    trigger: true
    passed: [ add-claimed-lock ]
  - aggregate:
    - get: runtime-ci
    - get: baba-yaga-env-director-state
    - get: cf-deployment-concourse-tasks
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_PROJECT_ID: {{baba_yaga_gcp_project}}
      BBL_GCP_REGION: us-central1
      BBL_GCP_ZONE: us-central1-a
      BBL_LB_CERT: {{baba_yaga_cf_ssl_cert}}
      BBL_LB_KEY: {{baba_yaga_cf_ssl_cert_private_key}}
      LB_DOMAIN: baba-yaga.cf-app.com
      BBL_ENV_NAME: baba-yaga-bbr
    input_mapping:
      bbl-state: baba-yaga-env-director-state
      ops-files: baba-yaga-env-director-state
    ensure:
      put: baba-yaga-env-director-state
      params:
        repository: updated-bbl-state
        rebase: true
  - put: bbr-pool
    params: {release: bbr-pool}

- name: destroy-infrastructure
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - put: bbr-pool
      params: {claim: baba-yaga}
    - get: baba-yaga-env-director-state
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
  - task: guarantee-no-existing-cf-deployment
    input_mapping:
      bbl-state: baba-yaga-env-director-state
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: baba-yaga-env-director-state
    ensure:
      put: baba-yaga-env-director-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: remove-claimed-lock
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - get: runtime-ci
  - get: bbr-pool
    passed: [ destroy-infrastructure ]
    trigger: true
  - task: prepare-to-modify-pool-resource
    file: runtime-ci/tasks/prepare-to-modify-pool-resource/task.yml
    params:
      NAME: baba-yaga
    output_mapping:
      pool-resource: bbr-pool
  - put: bbr-pool
    params: {remove: bbr-pool}

- name: run-bosh-cleanup
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: cf-deployment-concourse-tasks
      - get: baba-yaga-env-director-state
      - get: daily
        trigger: true
    - task: run-bosh-cleanup
      file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
      input_mapping:
        bbl-state: baba-yaga-env-director-state

- name: acquire-pool
  public: true
  serial: true
  plan:
  - aggregate:
    - get: cf-deployment-master
      trigger: true
    - put: bbr-pool
      params: {acquire: true}

- name: deploy
  public: true
  build_logs_to_retain: 100
  plan:
  - ensure:
      put: bbr-pool
      params: {release: bbr-pool}
    do:
    - get: bbr-pool
      trigger: true
      passed: [ acquire-pool ]
    - aggregate:
      - get: runtime-ci
      - get: cf-deployment-concourse-tasks
      - get: cf-deployment-master
      - get: baba-yaga-env-vars-store
      - get: baba-yaga-env-director-state
        passed: [ setup-infrastructure ]
      - get: baba-yaga-env-integration-configs
    - task: bosh-upload-stemcell
      file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
      input_mapping:
        cf-deployment: cf-deployment-master
        bbl-state: baba-yaga-env-director-state
      params:
        INFRASTRUCTURE: google
    - task: bosh-deploy-cf
      file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
      input_mapping:
        bbl-state: baba-yaga-env-director-state
        cf-deployment: cf-deployment-master
        ops-files: cf-deployment-master
        vars-store: baba-yaga-env-vars-store
        vars-files: baba-yaga-env-vars-store
      params:
        SYSTEM_DOMAIN: baba-yaga.cf-app.com
        OPS_FILES: "operations/use-compiled-releases.yml operations/experimental/enable-backup-restore.yml"
      ensure:
        put: baba-yaga-env-vars-store
        params:
          repository: updated-vars-store
          rebase: true
    - task: run-bosh-cleanup
      file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
      input_mapping:
        bbl-state: baba-yaga-env-director-state
    - task: update-integration-configs
      file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
      params:
        CATS_INTEGRATION_CONFIG_FILE: integration_config.json
      input_mapping:
        vars-store: baba-yaga-env-vars-store
        integration-configs: baba-yaga-env-integration-configs
      ensure:
        put: baba-yaga-env-integration-configs
        params:
          repository: updated-integration-configs
          rebase: true

- name: run-drats
  public: true
  build_logs_to_retain: 100
  plan:
  - on_success:
      put: bbr-pool
      params: {release: bbr-pool}
    do:
    - get: bbr-pool
      trigger: true
      passed: [ deploy ]
    - aggregate:
      - get: bbr-github-release
        trigger: true
      - get: baba-yaga-env-director-state
        passed: [ setup-infrastructure ]
      - get: baba-yaga-env-vars-store
      - get: drats-master
      - get: runtime-ci
    - task: run-drats
      file: runtime-ci/tasks/run-drats/task.yml
      input_mapping:
        disaster-recovery-acceptance-tests: drats-master
        bbr-binary-release: bbr-github-release
      params:
        SYSTEM_DOMAIN: baba-yaga.cf-app.com