groups:
- name: canibump
  jobs:
  - push-canibump

resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: canibump-repo
  type: git
  source:
    branch: master
    uri: https://github.com/dsabeti/redirect-cf-app.git
- name: canibump-app
  type: cf
  source:
    api: {{canibump_cf_api}}
    username: {{canibump_push_user}}
    password: {{canibump_push_password}}
    organization: {{canibump_org}}
    space: {{canibump_space}}

jobs:
- name: push-canibump
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: &timeout 4h
    do:
    - aggregate:
      - get: canibump-repo
      - get: runtime-ci
    - put: canibump-app
      params:
        manifest: canibump-repo/manifest.yml
        path: canibump-repo
