---
groups:
- name: cf-deployment
  jobs:
  - update-releases
  - deploy-releases
  - acceptance-tests
  - bless-manifest
- name: infrastructure
  jobs:
  - setup-infrastructure
  - destroy-infrastructure
  - verify-nameserver-has-record

resources:
- name: weekly
  type: time
  source:
    start: 3:00 -0700
    stop: 3:30 -0700
    interval: 168h
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: hermione-bbl-configuration
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hermione-env.git
    private_key: {{hermione_env_private_key}}
- name: hermione-deployment-configuration
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hermione-env.git
    private_key: {{hermione_env_private_key}}
- name: cf-deployment-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: {{cf_deployment_private_key}}
- name: cf-deployment-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: {{cf_deployment_private_key}}
- name: capi-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/capi-release
- name: nats-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/nats-release
- name: routing-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/cf-routing-release
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
- name: consul-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/consul-release
- name: etcd-release
  type: bosh-io-release
  source:
    repository: cloudfoundry-incubator/etcd-release
- name: diego-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/diego-release
- name: loggregator-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/loggregator
- name: cf-mysql-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-mysql-release
- name: uaa-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/uaa-release
- name: garden-linux-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-linux-release
- name: cflinuxfs2-rootfs-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cflinuxfs2-rootfs-release
- name: cf-release
  type: bosh-io-release
  source:
    repository: cloudfoundry/cf-release

jobs:
- name: destroy-infrastructure
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: hermione-bbl-configuration
    - get: runtime-ci
  - task: unbind-elb-from-r53
    file: runtime-ci/scripts/ci/unbind-elb-from-r53/task.yml
    input_mapping:
      env-repo: hermione-bbl-configuration
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      DOMAIN: hermione.cf-app.com
  - task: destroy-infrastructure
    file: runtime-ci/scripts/ci/destroy-infrastructure/task.yml
    input_mapping:
      env-repo: hermione-bbl-configuration
  - put: hermione-bbl-configuration
    params:
      repository: updated-env-repo
- name: setup-infrastructure
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: hermione-bbl-configuration
    - get: runtime-ci
  - task: setup-infrastructure
    file: runtime-ci/scripts/ci/setup-infrastructure/task.yml
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      BBL_LB_CERT: {{hermione_lbs_ssl_cert}}
      BBL_LB_KEY: {{hermione_lbs_ssl_signing_key}}
    input_mapping:
      env-repo: hermione-bbl-configuration
  - put: hermione-bbl-configuration
    params:
      repository: updated-env-repo
  - task: bind-elb-to-r53
    file: runtime-ci/scripts/ci/bind-elb-to-r53/task.yml
    input_mapping:
      env-repo: updated-env-repo
    params:
      AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
      DOMAIN: hermione.cf-app.com

- name: update-releases
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: hermione-bbl-configuration
    - get: cf-deployment-develop
    - get: hermione-deployment-configuration
    - get: capi-release
      trigger: true
    - get: stemcell
      trigger: true
    - get: nats-release
      trigger: true
      params:
        tarball: false
    - get: routing-release
      trigger: true
      params:
        tarball: false
    - get: consul-release
      trigger: true
      params:
        tarball: false
    - get: etcd-release
      trigger: true
      params:
        tarball: false
    - get: diego-release
      trigger: true
      params:
        tarball: false
    - get: loggregator-release
      trigger: true
      params:
        tarball: false
    - get: cf-mysql-release
      trigger: true
      params:
        tarball: false
    - get: uaa-release
      trigger: true
      params:
        tarball: false
    - get: garden-linux-release
      trigger: true
      params:
        tarball: false
    - get: cflinuxfs2-rootfs-release
      trigger: true
      params:
        tarball: false
    - get: cf-release
      trigger: true
      params:
        tarball: false
  - task: extract-director-creds-from-bbl
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
    input_mapping:
      env-repo: hermione-bbl-configuration
  - task: bosh-upload-stemcell
    file: runtime-ci/scripts/ci/bosh-upload-stemcell/task.yml
    params:
      TARGET_FILE: target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      CA_CERT_FILE: ca-cert
      STEMCELL_NAME: "*.tgz"
  - task: create-binaries-manifest-section
    file: runtime-ci/scripts/ci/create-binaries-manifest-section/task.yml
    input_mapping:
      deployment-configuration: cf-deployment-develop
  - task: commit-generated-manifest
    file: runtime-ci/scripts/ci/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      manifest: deployment-manifest
    params:
      MANIFEST_NAME: cf-deployment.yml
      MANIFEST_DESTINATION: cf-deployment.yml
      COMMIT_MESSAGE: 'Update releases'
  - put: cf-deployment-develop
    params:
      repository: updated-repo

- name: deploy-releases
  public: true
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-develop
      trigger: true
    - get: hermione-deployment-configuration
      trigger: true
    - get: hermione-bbl-configuration
  - task: extract-director-creds-from-bbl
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
    input_mapping:
      env-repo: hermione-bbl-configuration
  - task: bosh-deploy-cf
    file: runtime-ci/scripts/ci/bosh-deploy/task.yml
    input_mapping:
      manifest: cf-deployment-develop
      manifest-properties: hermione-deployment-configuration
    params:
      TARGET_FILE:  target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      CA_CERT_FILE: ca-cert
      MANIFEST_FILE: cf-deployment.yml
      DEPLOYMENT_VAR_FILE: deployment-env-vars.yml

- name: acceptance-tests
  public: true
  serial_groups: [hermione]
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: runtime-ci
      - get: cf-acceptance-tests
      - get: hermione-deployment-configuration
        trigger: true
        passed: [ deploy-releases ]
      - get: cf-deployment-develop
        trigger: true
        passed: [ deploy-releases ]
    - task: write-target-file-api
      file: runtime-ci/scripts/ci/write-target-file/task.yml
      params:
        TARGET: api.hermione.cf-app.com
    - task: enable-docker-diego
      file: runtime-ci/scripts/ci/enable-docker-diego/task.yml
      input_mapping:
        cf-target: target-file-dir
      params:
        CF_USER: {{hermione_admin_username}}
        CF_PASSWORD: {{hermione_admin_password}}
    - task: run-cats
      file: runtime-ci/scripts/ci/run-cats/task.yml
      params:
        INCLUDE_BACKEND_COMPATIBILITY: false
        INCLUDE_INTERNET_DEPENDENT: true
        INCLUDE_DIEGO_DOCKER: true
        INCLUDE_DIEGO_SSH: true
        INCLUDE_ROUTE_SERVICES: true
        INCLUDE_SECURITY_GROUPS: true
        INCLUDE_SERVICES: true
        INCLUDE_V3: false
        INCLUDE_PRIVILEGED_CONTAINER_SUPPORT: true
        INCLUDE_SSO: true
        BACKEND: diego
        CF_API: "api.hermione.cf-app.com"
        CF_ADMIN_USER: {{hermione_admin_username}}
        CF_ADMIN_PASSWORD: {{hermione_admin_password}}
        CF_APPS_DOMAIN: hermione.cf-app.com
        SKIP_SSL_VALIDATION: "true"
        USE_HTTP: "true"
        NODES: 6

- name: bless-manifest
  public: true
  serial: true
  build_logs_to_retain: 100
  plan:
    - do:
      - aggregate:
        - get: runtime-ci
        - get: hermione-deployment-configuration
          trigger: true
          passed: [ acceptance-tests ]
        - get: cf-deployment-develop
          trigger: true
          passed: [ acceptance-tests ]
        - get: cf-deployment-master
    - task: fast-forward-master-to-develop
      file: runtime-ci/scripts/ci/fast-forward-master-to-develop/task.yml
      input_mapping:
        master-repo: cf-deployment-master
        develop-repo: cf-deployment-develop
    - put: cf-deployment-master
      params:
        repository: fast-forwarded-master-repo

- name: verify-nameserver-has-record
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - get: runtime-ci
    - get: weekly
      trigger: true
    - task: verify-nameserver-has-record
      file: runtime-ci/scripts/ci/verify-nameserver-has-record/task.yml
      params:
        AWS_ACCESS_KEY_ID: {{hermione_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{hermione_aws_secret_access_key}}
        DOMAIN: hermione.cf-app.com
