---
groups:
- name: cf-smoke-tests-release
  jobs:
  - deploy-updated-smokes
  - run-smokes-errand
  - delete-smokes-deployment
  - create-final-release

resources:
# Weekly Trigger
- name: weekly-trigger
  type: time
  source:
    start: 3:00
    stop: 4:30
    location: America/Los_Angeles
    interval: 168h

# Concourse Tasks
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

# Releases
- name: cf-smoke-tests-release
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-smoke-tests-release.git
    private_key: ((cf_smoke_tests_readwrite_deploy_key.private_key))
    ignore_paths:
    - releases/**
    - .final_builds/**

- name: cf-cli-release
  type: bosh-io-release
  source:
    repository: bosh-packages/cf-cli-release

# ENV
- name: bellatrix-env-director-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/bellatrix-env.git
    private_key: ((bellatrix_env_readwrite_deploy_key.private_key))

# Semantic Version
- name: cf-smoke-tests-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/cf-relint-ci-semver.git
    branch: master
    private_key: ((cf_relint_ci_semver_readwrite_deploy_key.private_key))
    git_user: "CF MEGA BOT <cf-mega@pivotal.io>"
    file: cf-smoke-tests-version

jobs:
- name: deploy-updated-smokes
  build_logs_to_retain: 100
  serial_groups: [smoke_tests]
  public: true
  plan:
  - get: weekly-trigger
    trigger: true
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: cf-cli-release
    - get: cf-smoke-tests-release
      trigger: true
    - get: bellatrix-env-director-state
  - task: deploy-smoke-tests-errand
    file: runtime-ci/tasks/bosh-deploy-smokes/task.yml
    input_mapping:
      bbl-state: bellatrix-env-director-state
    params:
      SYSTEM_DOMAIN: bellatrix.cf-app.com

- name: run-smokes-errand
  build_logs_to_retain: 100
  serial_groups: [smoke_tests]
  public: true
  plan:
  - get: weekly-trigger
    passed: [deploy-updated-smokes]
    trigger: true
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-smoke-tests-release
      passed: [deploy-updated-smokes]
      trigger: true
    - get: bellatrix-env-director-state
  - task: run-smokes
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: bellatrix-env-director-state
    params:
      DEPLOYMENT_NAME: cf-smoke-tests
      ERRAND_NAME: smoke_tests
  - task: run-smokes-windows
    file: cf-deployment-concourse-tasks/run-errand/task.yml
    input_mapping:
      bbl-state: bellatrix-env-director-state
    params:
      DEPLOYMENT_NAME: cf-smoke-tests
      ERRAND_NAME: smoke_tests_windows

- name: delete-smokes-deployment
  build_logs_to_retain: 100
  serial_groups: [smoke_tests]
  public: true
  plan:
  - get: weekly-trigger
    passed: [run-smokes-errand]
    trigger: true
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-smoke-tests-release
      passed: [run-smokes-errand]
      trigger: true
    - get: bellatrix-env-director-state
  - task: delete-smoke-tests-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: bellatrix-env-director-state
    params:
      DEPLOYMENT_NAME: cf-smoke-tests

- name: create-final-release
  build_logs_to_retain: 100
  serial: true
  public: true
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-smoke-tests-release
      trigger: true
      passed: [run-smokes-errand]
    - get: semantic-version
      resource: cf-smoke-tests-version
      params: {bump: patch}
  - task: create-final-release
    file: runtime-ci/tasks/create-final-release/task.yml
    input_mapping:
      release-repo: cf-smoke-tests-release
    params:
      BLOBS_BUCKET_ACCESS_KEY_ID: ((cf_release_blobs_buckets_access_key_id))
      BLOBS_BUCKET_SECRET_KEY: ((cf_release_blobs_buckets_secrect_access_key))
  - put: cf-smoke-tests-release
    params:
      repository: final-release-repo
      rebase: true
      tag: semantic-version/version
  - put: cf-smoke-tests-version
    params: {bump: patch}
