---
groups:
- name: nats-release
  jobs:
    - deploy-nats
    - run-smoke-tests
    - setup-infrastructure

resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: nats-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/nats-release.git
- name: hagrid-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hagrid-env.git
    private_key: {{hagrid_env_private_key}}
- name: hagrid-env-updated
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hagrid-env.git
    private_key: {{hagrid_env_private_key}}
- name: aws-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-aws-xen-ubuntu-trusty-go_agent

jobs:
- name: setup-infrastructure
  public: true
  serial_groups: [nats-deploy]
  plan:
  - get: env-repo
    resource: hagrid-env
    trigger: true
  - get: runtime-ci
  - task: run-bbl
    file: runtime-ci/scripts/ci/setup-infrastructure/task.yml
    privileged: false
    params:
      AWS_ACCESS_KEY_ID: {{hagrid_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{hagrid_aws_secret_access_key}}
      BBL_LB_CERT: {{hagrid_bbl_lb_cert}}
      BBL_LB_KEY: {{hagrid_bbl_lb_key}}
    ensure:
      put: hagrid-env-updated
      params:
        repository: updated-env-repo

- name: deploy-nats
  public: true
  serial_groups: [nats-deploy]
  plan:
  - aggregate:
    - get: release-repo
      resource: nats-release
      trigger: true
    - get: env-repo
      trigger: true
      passed: [ setup-infrastructure ]
      resource: hagrid-env-updated
    - get: aws-stemcell
    - get: runtime-ci
  - task: extract-creds
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
  - task: create-release
    file: runtime-ci/scripts/ci/create-release/task.yml
    privileged: true
    params:
      RELEASE_NAME: nats
  - task: generate-deployment-manifest
    file: runtime-ci/scripts/ci/generate-nats-deployment-manifest-from-bbl/task.yml
    privileged: false
  - task: upload-release
    file: runtime-ci/scripts/ci/bosh-upload-release/task.yml
    input_mapping:
      release: release-tarball
    params:
      TARGET_FILE: target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      RELEASE_NAME: nats-*.tgz
  - task: bosh-deploy
    file: runtime-ci/scripts/ci/bosh-deploy/task.yml
    params:
      TARGET_FILE:   target
      USERNAME_FILE: username
      PASSWORD_FILE: password
      MANIFEST_FILE: nats.yml

- name: run-smoke-tests
  public: true
  serial_groups: [nats-deploy]
  plan:
  - aggregate:
    - get: nats-release
      trigger: true
      passed: [deploy-nats]
    - get: runtime-ci
    - get: env-repo
      resource: hagrid-env
  - task: extract-creds
    file: runtime-ci/scripts/ci/extract-director-creds-from-bbl/task.yml
    params:
      STATE_DIR_PATH: bbl-infrastructure
  - task: run-smoke-tests
    file: runtime-ci/scripts/ci/run-errand-bbl/task.yml
    input_mapping:
      target-file-dir: target
      bosh-user-file-dir: username
      bosh-password-file-dir: password
    params:
      BOSH_TARGET_FILE: target
      BOSH_USER_FILE: bosh-user-file-dir/username
      BOSH_PASSWORD_FILE: bosh-password-file-dir/password
      DEPLOYMENT_NAME: nats
      ERRAND_NAME: smoke-tests

