---
groups:
- name: nats-gcp
  jobs:
  - upload-stemcell
  - deploy-nats-standalone
- name: infrastructure
  jobs:
  - setup-infrastructure

resource_types:
- name: git
  type: docker-image
  source:
    repository: concourse/git-resource

resources:
- name: nats-release-develop
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/nats-release.git
    ignore_paths: [ .final_builds, releases ]
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: dobby-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dobby-env.git
    private_key: {{dobby_env_private_key}}
- name: dobby-env-infrastructure
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/dobby-env.git
    private_key: {{dobby_env_private_key}}
    paths:
    - infrastructure/*
- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

jobs:
- name: setup-infrastructure
  public: true
  serial_groups: [infrastructure]
  build_logs_to_retain: 100
  plan:
  - get: dobby-env-infrastructure
  - get: runtime-ci
  - task: setup-infrastructure-terraform
    file: runtime-ci/scripts/ci/setup-infrastructure-terraform/task.yml
    input_mapping:
      env-repo: dobby-env-infrastructure
  - put: dobby-env-infrastructure
    params:
      repository: updated-env-repo
  - task: bosh-create-env
    file: runtime-ci/scripts/ci/bosh-create-env/task.yml
    input_mapping:
      env-repo: updated-env-repo
      username: updated-env-repo
      password: updated-env-repo
    params:
      USERNAME_FILE: infrastructure/bosh-init/username
      PASSWORD_FILE: infrastructure/bosh-init/password
      DEPLOYMENT_VAR_FILE: infrastructure/bosh-init/deployment-env-vars.yml
  - put: dobby-env-infrastructure
    params:
      repository: updated-env-repo
  - task: bind-terraform-env-to-r53
    file: runtime-ci/scripts/ci/bind-terraform-env-to-r53/task.yml
    input_mapping:
      env-repo: updated-env-repo
    params:
      AWS_ACCESS_KEY_ID: {{dobby_aws_access_key_id}}
      AWS_SECRET_ACCESS_KEY: {{dobby_aws_secret_access_key}}
      DOMAIN: dobby.cf-app.com
  - task: bosh-update-cloud-config
    file: runtime-ci/scripts/ci/bosh-update-cloud-config/task.yml
    input_mapping:
      target: updated-env-repo
      username: updated-env-repo
      password: updated-env-repo
      ca-cert: updated-env-repo
      cloud-config: updated-env-repo
    params:
      TARGET_FILE:   infrastructure/bosh-init/bosh-target
      USERNAME_FILE: infrastructure/bosh-init/username
      PASSWORD_FILE: infrastructure/bosh-init/password
      CA_CERT_FILE:  infrastructure/bosh-init/certs/rootCA.pem
      CLOUD_CONFIG_FILE: infrastructure/bosh-init/cloud-config.yml


- name: upload-stemcell
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: dobby-env-infrastructure
      passed: [setup-infrastructure]
      trigger: true
    - get: gcp-stemcell
      trigger: true
  - task: bosh-upload-stemcell
    file: runtime-ci/scripts/ci/bosh-upload-stemcell/task.yml
    input_mapping:
      username: dobby-env-infrastructure
      password: dobby-env-infrastructure
      target: dobby-env-infrastructure
      ca-cert: dobby-env-infrastructure
      stemcell: gcp-stemcell
    params:
      TARGET_FILE: infrastructure/bosh-init/bosh-target
      USERNAME_FILE: infrastructure/bosh-init/username
      PASSWORD_FILE: infrastructure/bosh-init/password
      CA_CERT_FILE: infrastructure/bosh-init/certs/rootCA.pem
      STEMCELL_NAME: '*.tgz'

- name: deploy-nats-standalone
  public: true
  serial_groups: [nats-deploy]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: nats-release-develop
      trigger: true
    - get: dobby-env-infrastructure
      passed: [upload-stemcell]
    - get: gcp-stemcell
      passed: [upload-stemcell]
      params:
        tarball: false
    - get: runtime-ci
  - task: generate-nats-deployment-manifest
    file: runtime-ci/scripts/ci/generate-nats-deployment-manifest/task.yml
  - task: bosh-deploy-nats
    file: runtime-ci/scripts/ci/bosh-deploy-with-created-release/task.yml
    input_mapping:
      manifest-properties: dobby-env-infrastructure # we only need this resource to appease the interface for bosh-deploy-with-created-release/task.yml
      target: dobby-env-infrastructure
      username: dobby-env-infrastructure
      password: dobby-env-infrastructure
      ca-cert: dobby-env-infrastructure
      release: nats-release-develop
    params:
      TARGET_FILE:   infrastructure/bosh-init/bosh-target
      USERNAME_FILE: infrastructure/bosh-init/username
      PASSWORD_FILE: infrastructure/bosh-init/password
      CA_CERT_FILE:  infrastructure/bosh-init/certs/rootCA.pem
      MANIFEST_FILE: nats.yml
