---
groups:
- name: nats-release
  jobs:
  - deploy-nats-standalone
  - smoke-tests
- name: infrastructure
  jobs:
  - setup-infrastructure
  - destroy-infrastructure


resources:
# Manifests and Releases
- name: nats-release
  type: git
  source:
    branch: develop
    uri: https://github.com/cloudfoundry/nats-release.git

# Stemcell
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

# ENV
- name: myrtle-env-bbl-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/myrtle-env.git
    private_key: {{myrtle_env_git_deploy_key}}
    paths:
    - bbl-state.json
    - google_account_creds.json
# - name: myrtle-env-integration-configs
#   type: git
#   source:
#     branch: master
#     uri: git@github.com:cloudfoundry/myrtle-env.git
#     private_key: {{myrtle_env_git_deploy_key}}
#     paths:
#     - integration_config.json
#     - rats_integration_config.json
# - name: myrtle-env-vars-store
#   type: git
#   source:
#     branch: master
#     uri: git@github.com:cloudfoundry/myrtle-env.git
#     private_key: {{myrtle_env_git_deploy_key}}
#     paths:
#     - deployment-vars.yml

# Control
# - name: weekly
#   type: time
#   source:
#     start: 3:00 -0700
#     stop: 3:30 -0700
#     interval: 168h
# - name: daily
#   type: time
#   source:
#     start: 3:00 -0700
#     stop: 3:30 -0700
#     interval: 24h

# Concourse Tasks
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v0.*
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

jobs:
- name: setup-infrastructure
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: myrtle-env-bbl-state
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_PROJECT_ID: {{myrtle_gcp_project}}
      BBL_GCP_REGION: us-central1
      BBL_GCP_ZONE: us-central1-a
      BBL_LB_CERT: {{myrtle_cf_ssl_cert}}
      BBL_LB_KEY: {{myrtle_cf_ssl_cert_private_key}}
      LB_DOMAIN: myrtle.cf-app.com
      BBL_ENV_NAME: myrtle-nats
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    ensure:
      put: myrtle-env-bbl-state
      params:
        repository: updated-bbl-state

- name: destroy-infrastructure
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: myrtle-env-bbl-state
    - get: cf-deployment-concourse-tasks
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    ensure:
      put: myrtle-env-bbl-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-nats-standalone
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: stemcell
      trigger: true
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [setup-infrastructure]
    - get: nats-release
      trigger: true
    - get: runtime-ci
  - task: deploy-nats
    file: runtime-ci/scripts/ci/bosh-deploy-nats/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state

- name: smoke-tests
  public: true
  serial_groups: [myrtle]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: nats-release
      trigger: true
      passed: [deploy-nats-standalone]
    - get: runtime-ci
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [deploy-nats-standalone]
  - task: run-errand-smoke-tests
    file: runtime-ci/tasks/run-errand/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    params:
      DEPLOYMENT_NAME: nats
      ERRAND_NAME: smoke-tests
