---
groups:
- name: nats-release
  jobs:
  - deploy-nats-standalone
  - smoke-tests
  - delete-nats-standalone
  - deploy-cf-with-created-nats
  - cf-acceptance-tests
  - delete-cf-deployment
  - create-final-release
- name: infrastructure
  jobs:
  - setup-infrastructure
  - destroy-infrastructure

resources:
# Manifests and Releases
- name: nats-release
  type: git
  source:
    branch: develop
    private_key: {{nats_release_read_write_deploy_key}}
    uri: git@github.com:cloudfoundry/nats-release.git
- name: nats-release-master
  type: git
  source:
    branch: master
    private_key: {{nats_release_read_write_deploy_key}}
    uri: git@github.com:cloudfoundry/nats-release.git
- name: cf-deployment-master
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment.git
- name: cf-acceptance-tests
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-acceptance-tests.git
- name: cats-concourse-task
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cats-concourse-task.git

# Stemcell
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

# ENV
- name: myrtle-env-bbl-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/myrtle-env.git
    private_key: {{myrtle_env_git_deploy_key}}
    paths:
    - bbl-state.json
    - google_account_creds.json
- name: myrtle-env-vars-store
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/myrtle-env.git
    private_key: {{myrtle_env_git_deploy_key}}
    paths:
    - deployment-vars.yml
- name: myrtle-env-integration-configs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/myrtle-env.git
    private_key: {{myrtle_env_git_deploy_key}}
    paths:
    - cats_integration_config.json

# Control
- name: weekly
  type: time
  source:
    interval: 168h
    location: US/Pacific
    start: 9:00 AM
    stop: 10:00 AM
    days: [Tuesday]

# Concourse Tasks
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
    tag_filter: v3.*
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

jobs:
- name: setup-infrastructure
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: myrtle-env-bbl-state
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: google_account_creds.json
      BBL_GCP_PROJECT_ID: {{myrtle_gcp_project}}
      BBL_GCP_REGION: us-central1
      BBL_GCP_ZONE: us-central1-a
      BBL_LB_CERT: {{myrtle_cf_ssl_cert}}
      BBL_LB_KEY: {{myrtle_cf_ssl_cert_private_key}}
      LB_DOMAIN: myrtle.cf-app.com
      BBL_ENV_NAME: myrtle-nats
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    ensure:
      put: myrtle-env-bbl-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: destroy-infrastructure
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: myrtle-env-bbl-state
    - get: cf-deployment-concourse-tasks
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    ensure:
      put: myrtle-env-bbl-state
      params:
        repository: updated-bbl-state
        rebase: true

- name: deploy-nats-standalone
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: stemcell
      trigger: true
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [setup-infrastructure]
    - get: nats-release
      trigger: true
    - get: runtime-ci
    - get: weekly
      trigger: true
  - task: deploy-nats
    file: runtime-ci/scripts/ci/bosh-deploy-nats/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state

- name: smoke-tests
  public: true
  serial_groups: [myrtle]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: nats-release
      trigger: true
      passed: [deploy-nats-standalone]
    - get: runtime-ci
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [deploy-nats-standalone]
    - get: weekly
      trigger: true
      passed: [deploy-nats-standalone]
  - task: run-errand-smoke-tests
    file: runtime-ci/tasks/run-errand/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    params:
      DEPLOYMENT_NAME: nats
      ERRAND_NAME: smoke-tests

- name: delete-nats-standalone
  public: true
  serial_groups: [myrtle]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [smoke-tests]
    - get: nats-release
      trigger: true
      passed: [smoke-tests]
    - get: weekly
      trigger: true
      passed: [smoke-tests]
  - task: delete-nats-standalone
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
    params:
      DEPLOYMENT_NAME: nats

- name: deploy-cf-with-created-nats
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: cf-deployment-master
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [smoke-tests]
    - get: myrtle-env-vars-store
    - get: myrtle-env-integration-configs
    - get: nats-release
      trigger: true
      passed: [smoke-tests]
    - get: weekly
      trigger: true
      passed: [smoke-tests]
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcell-from-cf-deployment/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
      cf-deployment: cf-deployment-master
  - task: deploy-cf-with-created-nats
    file: cf-deployment-concourse-tasks/bosh-deploy-with-created-release/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state
      cf-deployment: cf-deployment-master
      release: nats-release
      ops-files: cf-deployment-master
      vars-store: myrtle-env-vars-store
      vars-files: myrtle-env-vars-store
    params:
      SYSTEM_DOMAIN: myrtle.cf-app.com
    ensure:
      put: myrtle-env-vars-store
      params:
        repository: updated-vars-store
        rebase: true
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    input_mapping:
      vars-store: myrtle-env-vars-store
      integration-configs: myrtle-env-integration-configs
    ensure:
      put: myrtle-env-integration-configs
      params:
        repository: updated-integration-configs
        rebase: true
  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state

- name: cf-acceptance-tests
  serial_groups: [myrtle]
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cats-concourse-task
    - get: cf-acceptance-tests
    - get: cf-deployment-master
      passed: [deploy-cf-with-created-nats]
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [deploy-cf-with-created-nats]
    - get: myrtle-env-vars-store
      passed: [deploy-cf-with-created-nats]
    - get: myrtle-env-integration-configs
    - get: cf-deployment-concourse-tasks
    - get: nats-release
      passed: [deploy-cf-with-created-nats]
      trigger: true
    - get: weekly
      trigger: true
      passed: [deploy-cf-with-created-nats]
  - task: set-cats-feature-flags
    file: cf-deployment-concourse-tasks/set-feature-flags/task.yml
    input_mapping:
      vars-store: myrtle-env-vars-store
    params:
      SYSTEM_DOMAIN: myrtle.cf-app.com
  - task: run-cats
    input_mapping:
    - integration-config: myrtle-env-integration-configs
    file: cats-concourse-task/task.yml
    params:
      CONFIG_FILE_PATH: cats_integration_config.json

- name: delete-cf-deployment
  public: true
  serial_groups: [myrtle]
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
    - get: myrtle-env-bbl-state
      trigger: true
      passed: [cf-acceptance-tests]
    - get: nats-release
      trigger: true
      passed: [cf-acceptance-tests]
    - get: weekly
      trigger: true
      passed: [cf-acceptance-tests]
  - task: delete-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: myrtle-env-bbl-state

- name: create-final-release
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: nats-release
      passed: [cf-acceptance-tests]
      trigger: true
    - get: nats-release-master
  - task: create-final-release
    file: runtime-ci/scripts/ci/create-final-release/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
    params:
      RELEASE_NAME: nats
      BLOBS_BUCKET_ACCESS_KEY_ID: {{nats_release_blobs_buckets_access_key_id}}
      BLOBS_BUCKET_SECRET_KEY: {{nats_release_blobs_buckets_secrect_access_key}}
  - put: nats-release-master
    params:
      repository: final-release-repo
      tag: final-release-repo/version_number
      tag_prefix: v
  - task: merge-master-into-develop
    file: runtime-ci/scripts/ci/merge-master-into-develop/task.yml
    input_mapping:
      release-repo-master: nats-release-master
      release-repo: nats-release
  - put: nats-release
    params:
      repository: final-release-repo
