---
groups:
- name: cf-deployment
  jobs:
  - fail-prs-to-cf-deployment-master
  - pass-prs-to-cf-deployment-develop
  - run-unit-tests-on-all-cf-deployment-prs

- name: cf-release
  jobs:
  - fail-prs-to-cf-release-master
  - pass-prs-to-cf-release-develop
  - run-unit-tests-on-all-cf-release-prs

- name: nats-release
  jobs:
  - fail-prs-to-nats-release-master
  - pass-prs-to-nats-release-develop

resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr
      tag: v25

resources:
  - name: runtime-ci
    type: git
    source:
      branch: master
      uri: https://github.com/cloudfoundry/runtime-ci.git

  - name: cf-deployment-all-branches
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-deployment
  - name: cf-deployment-master
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-deployment
      base: master
  - name: cf-deployment-develop
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-deployment
      base: develop

  - name: cf-release-all-branches
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-release
  - name: cf-release-master
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-release
      base: master
  - name: cf-release-develop
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/cf-release
      base: develop

  - name: nats-release-master
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/nats-release
      base: master
  - name: nats-release-develop
    type: pull-request
    source:
      access_token: {{github_status_bot_repo_access_token}}
      repo: cloudfoundry/nats-release
      base: develop

jobs:
  - name: fail-prs-to-cf-deployment-master
    public: true
    build_logs_to_retain: 100
    plan:
      - get: cf-deployment-master
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - task: write-pr-check-failure-comment
        file: runtime-ci/tasks/write-pr-check-failure-comment/task.yml
        input_mapping:
          pull-request: cf-deployment-master
      - put: cf-deployment-master
        params:
          path: cf-deployment-master
          status: failure
          context: {{pr_context}}
          comment: pull-request-comment/comment
  - name: pass-prs-to-cf-deployment-develop
    public: true
    build_logs_to_retain: 100
    plan:
      - get: cf-deployment-develop
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - put: cf-deployment-develop
        params:
          path: cf-deployment-develop
          status: success
          context: {{pr_context}}

  - name: run-unit-tests-on-all-cf-deployment-prs
    public: true
    build_logs_to_retain: 100
    plan:
    - timeout: 4h
      do:
      - aggregate:
        - get: runtime-ci
        - get: cf-deployment-all-branches
          trigger: true
          version: every
      - put: cf-deployment-all-branches
        params:
          path: cf-deployment-all-branches
          status: pending
          context: {{unit_tests_context}}
      - task: unit-test-ops-files
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: relintdockerhubpushbot/bosh-cli
          inputs:
          - name: cf-deployment-all-branches
          run:
            dir: cf-deployment-all-branches
            path: scripts/test
        on_failure:
          do:
          - task: write-pr-check-failure-comment
            file: runtime-ci/tasks/write-pr-check-failure-comment/task.yml
            input_mapping:
              pull-request: cf-deployment-all-branches
          - put: cf-deployment-all-branches
            params:
              path: cf-deployment-all-branches
              status: failure
              context: {{unit_tests_context}}
              comment: pull-request-comment/comment
        on_success:
          put: cf-deployment-all-branches
          params:
            path: cf-deployment-all-branches
            status: success
            context: {{unit_tests_context}}

  - name: fail-prs-to-cf-release-master
    public: true
    build_logs_to_retain: 100
    plan:
      - get: cf-release-master
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - task: write-pr-check-failure-comment
        file: runtime-ci/tasks/write-pr-check-failure-comment/task.yml
        input_mapping:
          pull-request: cf-release-master
      - put: cf-release-master
        params:
          path: cf-release-master
          status: failure
          context: {{pr_context}}
          comment: pull-request-comment/comment
  - name: pass-prs-to-cf-release-develop
    public: true
    build_logs_to_retain: 100
    plan:
      - get: cf-release-develop
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - put: cf-release-develop
        params:
          path: cf-release-develop
          status: success
          context: {{pr_context}}

  - name: run-unit-tests-on-all-cf-release-prs
    public: true
    build_logs_to_retain: 100
    plan:
    - timeout: 4h
      do:
      - aggregate:
        - get: runtime-ci
        - get: cf-release-all-branches
          trigger: true
          version: every
      - put: cf-release-all-branches
        params:
          path: cf-release-all-branches
          status: pending
          context: {{unit_tests_context}}
      - task: run-cf-release-unit-tests
        privileged: true
        file: runtime-ci/scripts/ci/run-cf-release-unit-tests/task.yml
        input_mapping:
            cf-release-develop: cf-release-all-branches
        params:
          CF_RELEASE_DIR: 'cf-release-develop'
        on_failure:
          do:
          - task: write-pr-check-failure-comment
            file: runtime-ci/tasks/write-pr-check-failure-comment/task.yml
            input_mapping:
              pull-request: cf-release-all-branches
          - put: cf-release-all-branches
            params:
              path: cf-release-all-branches
              status: failure
              context: {{unit_tests_context}}
              comment: pull-request-comment/comment
        on_success:
          put: cf-release-all-branches
          params:
            path: cf-release-all-branches
            status: success
            context: {{unit_tests_context}}

  - name: fail-prs-to-nats-release-master
    public: true
    build_logs_to_retain: 100
    plan:
      - get: nats-release-master
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - task: write-pr-check-failure-comment
        file: runtime-ci/tasks/write-pr-check-failure-comment/task.yml
        input_mapping:
          pull-request: nats-release-master
      - put: nats-release-master
        params:
          path: nats-release-master
          status: failure
          context: {{pr_context}}
          comment: pull-request-comment/comment
  - name: pass-prs-to-nats-release-develop
    public: true
    build_logs_to_retain: 100
    plan:
      - get: nats-release-develop
        trigger: true
        version: every
        params:
          git:
            submodules: none
            depth: 1
      - put: nats-release-develop
        params:
          path: nats-release-develop
          status: success
          context: {{pr_context}}
