groups:
- name: runtime-ci
  jobs:
  - test-runtime-ci
  - all-jobs-public
  - verify-every-task-has-docker-image

resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

jobs:
- name: all-jobs-public
  public: true
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: validate-all-jobs-public
    file: runtime-ci/scripts/ci/validate-all-jobs-public/task.yml

- name: test-runtime-ci
  public: true
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: run-tests
    file: runtime-ci/scripts/ci/runtime-ci-tests/task.yml

- name: verify-every-task-has-docker-image
  public: true
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: verify-every-task-has-docker-image
    file: runtime-ci/scripts/ci/verify-every-task-has-docker-image/task.yml
