groups:
- name: runtime-dev-envs
  jobs:
  - green-means-nothing-deployed-on-runtime1
  - green-means-nothing-deployed-on-runtime2

resources:
- name: every-15-minutes
  type: time
  source:
    interval: 15m

- name: runtime-ci
  type: git
  source:
    uri: https://github.com/cloudfoundry/runtime-ci.git
    branch: master

jobs:
- name: green-means-nothing-deployed-on-runtime1
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: every-15-minutes
      trigger: true
    - get: runtime-ci
      trigger: true
  - task: check-deployments
    file: runtime-ci/scripts/ci/check-deployment/task.yml
    params:
      BOSH_USER: {{runtime_1_bosh_user}}
      BOSH_PASSWORD: {{runtime_1_bosh_password}}
      BOSH_TARGET: micro.runtime1.cf-app.com

- name: green-means-nothing-deployed-on-runtime2
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: every-15-minutes
      trigger: true
    - get: runtime-ci
      trigger: true
  - task: check-deployments
    file: runtime-ci/scripts/ci/check-deployment/task.yml
    params:
      BOSH_USER: {{runtime_2_bosh_user}}
      BOSH_PASSWORD: {{runtime_2_bosh_password}}
      BOSH_TARGET: micro.runtime2.cf-app.com
