resources:
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git

- name: daily
  type: time
  source:
    start: 3:00 -0700
    stop: 4:30 -0700
    interval: 24h

jobs:
- name: all-jobs-public
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: validate-all-jobs-public
    file: runtime-ci/tasks/validate-all-jobs-public/task.yml

- name: verify-every-task-is-used-in-a-pipeline
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: verify-every-task-is-used-in-a-pipeline
    file: runtime-ci/tasks/verify-every-task-is-used-in-a-pipeline/task.yml

- name: stale-job-alert
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: daily
      trigger: true
    - get: runtime-ci
  - task: stale-job-alert
    file: runtime-ci/tasks/stale-job-alert/task.yml

- name: run-update-manifest-releases-unit-tests
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
      trigger: true
  - task: run-update-manifest-releases-unit-tests
    file: runtime-ci/tasks/run-update-manifest-releases-unit-tests/task.yml
