---
groups:
- name: tmp-hagrid-credhub
  jobs:
  - hagrid-deploy
  - hagrid-cats

resources:
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: cf-deployment-master-5.1
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
    tag_filter: v5.1.0
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: hagrid-env-integration-configs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hagrid-env.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))
    paths:
    - integration_config.json
    - cats_windows2016_integration_config.json
- name: hagrid-env-director-state
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/hagrid-env.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))
- name: cf-acceptance-tests-master
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/cf-acceptance-tests.git
    private_key: ((cf_acceptance_tests_readwrite_deploy_key.private_key))

jobs:
- name: hagrid-deploy
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-master-5.1
    - get: cf-deployment-concourse-tasks
    - get: runtime-ci
    - get: hagrid-env-integration-configs
    - get: hagrid-env-director-state
  - task: bosh-upload-stemcell-upgrade
    file: cf-deployment-concourse-tasks/bosh-upload-stemcells/task.yml
    input_mapping:
      cf-deployment: cf-deployment-master-5.1
      bbl-state: hagrid-env-director-state
      ops-files: cf-deployment-master-5.1
    params:
      INFRASTRUCTURE: google
      OPS_FILES: |
        operations/windows2016-cell.yml
  - task: collect-ops-files
    file: cf-deployment-concourse-tasks/collect-ops-files/task.yml
    input_mapping:
      base-ops-files: cf-deployment-master-5.1
      new-ops-files: hagrid-env-director-state
    params:
      BASE_OPS_FILE_DIR: operations
      NEW_OPS_FILES: |
        update-stemcell.yml
        update-credhub.yml
  - task: bosh-deploy-cf
    file: cf-deployment-concourse-tasks/bosh-deploy/task.yml
    input_mapping:
      bbl-state: hagrid-env-director-state
      cf-deployment: cf-deployment-master-5.1
      ops-files: collected-ops-files
      vars-files: hagrid-env-director-state
    params:
      SYSTEM_DOMAIN: hagrid.cf-app.com
      OPS_FILES: |
        operations/update-stemcell.yml
        operations/windows2016-cell.yml
        operations/experimental/use-compiled-releases-windows.yml
        operations/enable-service-discovery.yml
        operations/update-credhub.yml
        operations/experimental/fast-deploy-with-downtime-and-danger.yml
      DEPLOY_WITH_UPTIME_MEASUREMENTS: false
      MEASURE_SYSLOG_AVAILABILITY: true
      FAIL_ON_DOWNTIME: true
      TCP_DOMAIN: tcp.hagrid.cf-app.com
      AVAILABLE_PORT: 1100
      HTTP_AVAILABILITY_THRESHOLD: 0
      APP_PUSHABILITY_THRESHOLD: 2
      RECENT_LOGS_THRESHOLD: 8
      STREAMING_LOGS_THRESHOLD: 2
      APP_SYSLOG_AVAILABILITY_THRESHOLD: 12
  - task: run-bosh-cleanup
    file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
    input_mapping:
      bbl-state: hagrid-env-director-state
  - task: update-integration-configs
    file: cf-deployment-concourse-tasks/update-integration-configs/task.yml
    params:
      CATS_INTEGRATION_CONFIG_FILE: integration_config.json
      WATS_INTEGRATION_CONFIG_FILE: cats_windows2016_integration_config.json
    input_mapping:
      bbl-state: hagrid-env-director-state
      integration-configs: hagrid-env-integration-configs
    ensure:
      put: hagrid-env-integration-configs
      params:
        repository: updated-integration-configs
        rebase: true
  - task: open-asgs-for-credhub
    file: runtime-ci/tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: hagrid-env-director-state
    params:
      INSTANCE_GROUP_NAME: credhub
      SYSTEM_DOMAIN: hagrid.cf-app.com
      SECURITY_GROUP_NAME: credhub
  - task: open-asgs-for-uaa
    file: runtime-ci/tasks/open-asgs-for-bosh-instance-group/task.yml
    input_mapping:
      bbl-state: hagrid-env-director-state
    params:
      INSTANCE_GROUP_NAME: uaa
      SYSTEM_DOMAIN: hagrid.cf-app.com
      SECURITY_GROUP_NAME: uaa

- name: hagrid-cats
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: cf-deployment-concourse-tasks
      - get: cf-acceptance-tests-master
      - get: hagrid-env-integration-configs
    - task: run-cats
      file: cf-deployment-concourse-tasks/run-cats/task.yml
      input_mapping:
        integration-config: hagrid-env-integration-configs
        cf-acceptance-tests: cf-acceptance-tests-master
      params:
        CAPTURE_LOGS: true
        RELINT_VERBOSE_AUTH: "true"
