---
groups:
- name: maxime-uptimer
  jobs:
  - test-uptime

resources:
- name: maxime-env
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/maxime-env.git
    private_key: ((maxime_env_readwrite_deploy_key.private_key))
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git

jobs:
  - name: test-uptime
    public: true
    serial: true
    build_logs_to_retain: 100
    plan:
    - timeout: 4h
      do:
      - aggregate:
        - get: cf-deployment-concourse-tasks
        - get: bbl-state
          resource: maxime-env
      - task: test-uptime
        file: bbl-state/tasks/run-uptimer/task.yml
