---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: manifest
- name: runtime-ci

outputs:
- name: exported-release

run:
  path: runtime-ci/tasks/compile-release-from-manifest/task

params:
  BBL_STATE_DIR: bbl-state
  RELEASE_NAME:
  MANIFEST_FILENAME: cf-deployment.yml
  STEMCELL_OS: ubuntu-trusty
