---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: release-repo
- name: runtime-ci

params:
  GH_ACCESS_TOKEN: ~
  RELEASE_NAME: cf

run:
  path: runtime-ci/tasks/publish-release-notes-draft/task
