---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
- name: runtime-ci
- name: cf-deployment
- name: ops-files
# - name: stemcell

run:
  path: runtime-ci/tasks/bosh-dry-run-docker-cpi/task

params:
  VARS_FILES:
