---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state

run:
  path: runtime-ci/tasks/update-cloud-config-from-bbl/task

params:
  BBL_STATE_DIR:
