---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: original-ops-file
- name: deployment-configuration # repo containing the original manifest
- name: release
- name: stemcell
- name: compiled-release-tarball
  optional: true
- name: current-commit-message
  optional: true

outputs:
- name: commit-message
- name: updated-deployment-manifest
- name: updated-ops-file

run:
  path: runtime-ci/tasks/update-single-release/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  UPDATED_DEPLOYMENT_MANIFEST_PATH: cf-deployment.yml
  RELEASE_NAME: 
  TARGET: manifest
  # Either `manifest`, `opsfile` or `compiledReleasesOpsfile`
  # If `manifest` is specified, then the following needs to be filled:
  #   ORIGINAL_DEPLOYMENT_MANIFEST_PATH
  #   UPDATED_DEPLOYMENT_MANIFEST_PATH
  # If `opsfile` or `compiledReleasesOpsfile` is specified then the following needs to be filled:
  #   ORIGINAL_OPS_FILE_PATH
  #   UPDATED_OPS_FILE_PATH
  ORIGINAL_OPS_FILE_PATH:
  UPDATED_OPS_FILE_PATH:
