---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: original-ops-file
- name: windows2016fs-release


outputs:
- name: commit-message
- name: updated-ops-file

run:
  path: runtime-ci/tasks/update-windows-releases/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_OPS_FILE_PATH: operations/use-offline-windows2016fs.yml
  UPDATED_OPS_FILE_PATH: use-offline-windows2016fs.yml
