---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
- name: runtime-ci
- name: original-ops-file
- name: garden-windows-release
- name: hwc-buildpack-release
- name: windows-utilities-release

outputs:
- name: commit-message
- name: updated-ops-file

run:
  path: runtime-ci/tasks/update-windows-releases/task

params:
  COMMIT_MESSAGE_PATH: commit-message.txt
  ORIGINAL_OPS_FILE_PATH: operations/windows-cell.yml
  UPDATED_OPS_FILE_PATH: windows-cell.yml
  OFFLINE: false
