---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci

run:
  path: runtime-ci/tasks/ensure-api-healthy/task

params:
  SYSTEM_DOMAIN:
