---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state  # - The Director's environment repo
- name: runtime-ci  # This repo
- name: cf-deployment-concourse-tasks

params:
  BBL_STATE_DIR: bbl-state

run:
  path: runtime-ci/tasks/bosh-delete-loggregator-release/task
