---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-and-spiff

inputs:
- name: bbl-state
- name: cf-deployment
- name: runtime-ci
- name: vars-store

outputs:
- name: env_repo_with_vars_store

run:
  path: runtime-ci/tasks/r2d2/task
