---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci

run:
  path: runtime-ci/tasks/validate-all-jobs-public/task

params:
  RUNTIME_CI_DIR: runtime-ci
