---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: bbl-state
- name: runtime-ci

run:
  path: runtime-ci/tasks/run-errand/task

params:
  DEPLOYMENT_NAME:
  ERRAND_NAME:
