---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/verify-every-task-is-used-in-a-pipeline

inputs:
- name: runtime-ci

run:
  path: runtime-ci/scripts/ci/verify-every-task-is-used-in-a-pipeline/task
