---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-cli

inputs:
- name: runtime-ci
- name: bbl-state
run:
  path: runtime-ci/tasks/recreate-database/task

params:
  BBL_STATE_DIR:
  DB_HOST:
  DB_USER:
  DB_PASSWORD:
  DB_NAME:
  BOSH_GW_USER: jumpbox
