---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/relint-base

inputs:
- name: runtime-ci
- name: cf-deployment-develop

outputs:
- name: updated-cf-deployment-manifest

run:
  path: runtime-ci/tasks/record-cfd-version-in-manifest/task
