
[[dependencies]]
  branch = "master"
  name = "github.com/onsi/ginkgo"

[[dependencies]]
  branch = "master"
  name = "github.com/onsi/gomega"

[[dependencies]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
