---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/bosh-and-spiff

inputs:
- name: release-repo
- name: stubs-repo
- name: runtime-ci

outputs:
- name: manifest

run:
  path: runtime-ci/tasks/generate-release-manifest/task

params:
  INFRASTRUCTURE:
  STUBS_PATH:
